### ISSUE TITLE
Use Debian 8 for base instead of Ubuntu 16.04

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-image-solr#1]
...doing this would allow for a bit of a smaller base image download. It only takes about 25s with my current infrastructure, but half the image size leaves more disk space for indexes and filesystem optimization, and can also cut down the initial `docker run` time to ~15s.

I am also willing to consider basing it on CentOS 7—either would be more efficient than Ubuntu. The only reason I'm starting here is my current non-Docker infra is using Ubuntu for boring historical reasons, and I'm lazy.

**Comment by geerlingguy** [comment]
As a quick note, both Ansible roles in use support any of the above OSes.

**Comment by geerlingguy** [comment]
Another important note that turns me away from Ubuntu. With the default settings I'd like to use, I'm running into 100% CPU usage unless I add some annoying workarounds due to some weird TTY issues on Ubuntu-based containers :/

**Comment by geerlingguy** [comment]
For Ubuntu, I used:

```yaml
    - name: Install repo for Java 8 (Ubuntu).
      apt_repository: repo=ppa:openjdk-r/ppa
      update_cache: yes
      when: ansible_distribution == 'Ubuntu'
```

And for Debian:

```yaml
    - name: Install repo for Java 8 (Debian).
      apt_repository:
        repo: 'deb http://http.debian.net/debian jessie-backports main contrib non-free'
        state: present
        update_cache: yes
      when: ansible_distribution == 'Debian'
```

Both distributions use the same `openjdk-8-jdk` package, it seems.
